### ISSUE TITLE
Header navbar is not responsive in mobile

### ISSUE THREAD

**Issue by bharathjinka09** [divanov11/Mumble#114]
Hi all,

Navbar is not responsive in mobile.
I am attaching the screenshot. 
If it is a drop-down navbar for smaller size screens, then it will look good.

![Screenshot_2021-04-03-13-22-25-329_com android chrome](https://user-images.githubusercontent.com/33654188/113472324-15f47880-9480-11eb-957b-5bb44ed41ccf.jpg)

Thanks 👍

**Comment by MidouWebDev** [comment]
I will do my best to work on it for sure !

**Comment by bharathjinka09** [comment]
It's working fine 😀
