### ISSUE TITLE
SearchBox in Header has alignment issues

### ISSUE THREAD

**Issue by mani-barathi** [divanov11/Mumble#116]
Input and the icon inside the SearchBox has some alignment issue

**Comment by Mr-spShuvo** [comment]
Can you attached a preview of your issue on your side before the changes you have made. @mani-barathi

**Comment by mani-barathi** [comment]
@Mr-spShuvo I Have attached before and after preview in PR #117 , check that.
Previously in css we have used absolute and relative position to get the icon and input field stick together, now I figured out there was a better way in doing that without css position
