### ISSUE TITLE
Search by People is not responsive

### ISSUE THREAD

**Issue by bharathjinka09** [divanov11/Mumble#118]
Search by People is not responsive.
 I am attaching the screenshot.
If the card size is reduced, then it will look good.

![Screenshot_2021-04-03-22-15-15-168_com android chrome](https://user-images.githubusercontent.com/33654188/113485363-b4a5c700-94ca-11eb-8373-20f65acdce84.jpg)
Thanks 👍

**Comment by divanov11** [comment]
Fixed :)
