### ISSUE TITLE
Deploy Previews - Netlify 

### ISSUE THREAD

**Issue by felixfaisal** [divanov11/Mumble#119]
**Is your feature request related to a problem? Please describe.**
I remember in Denis's stream, Him mentioning that in many PRs that frontend seems to be altered or something he didn't want to be added or changed. 
It would be a tedious procedure to go through the entire code to know if something in the frontend has changed and how it affects the overall application

**Describe the solution you'd like**
It would be great to have Netlify Deploy Previews, Previews will be created for every PR made, so you can easily visualize the changes that have been made, As it gets deployed and a URL is provided 

**Describe alternatives you've considered**
An alternative would be to use Github Pages, but it's tedious as compared to Netlify, as it's just an App and you have to integrate it with the repo, while for the Github Pages you'd have to create an Action 

**Add additional instructions and considerations for the assignee**
Reading material 
[Information/Instruction](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/)

**Comment by codyseibert** [comment]
Thanks for posting the issue. This sounds like a cool idea!

**Comment by felixfaisal** [comment]
I think this has been added using Vercel, We can close this issue :)

**Comment by Mr-spShuvo** [comment]
We are using vercel.
