### ISSUE TITLE
Bug in Header Dropdowns

### ISSUE THREAD

**Issue by mani-barathi** [divanov11/Mumble#120]
**Bug in Header**
when the notification drop down is active and if the user click on the avatar dropdown, notification drop down is not closing as well as the avatar dropdown is not opening

**To Reproduce**
Steps to reproduce the behaviour:

1. Click the bell icon in header (notification dropdown opens)
2. Now leaving the notification drop down open, click on the avatar

**Expected behaviour**
notification dropdown should close and avatar dropdown should open

**Screenshot**
![preview2](https://user-images.githubusercontent.com/49336839/113487896-449e3d80-94d8-11eb-81e3-9b1146374280.gif)

**Comment by divanov11** [comment]
Just noticed this. If you want to take this section. If you want to take care of this its all yours :)
