### ISSUE TITLE
Bug in updating user skills modal

### ISSUE THREAD

**Issue by mohammad4kh** [divanov11/Mumble#122]
**Describe the bug**

There is a bug when edit the skills then press update without adding or removing any thing

**To Reproduce**

1. Go to user settings page
2. In skills section click on edit
3. Without adding or removing any skill press update
4. An error will show up

![Peek 2021-04-03 21-55](https://user-images.githubusercontent.com/6501582/113490044-0a2ca480-94c8-11eb-9fe5-594a251109b6.gif)

**Comment by gmrzone** [comment]
Fixing it now..
