### ISSUE TITLE
Create Discussion Component / Route

### ISSUE THREAD

**Issue by codyseibert** [divanov11/Mumble#125]
There currently is no page for creating a new discussion.  We have a link called "Start a Discussion", but it doesn't navigate the user to any usable page.  This feature would include the following work:

- create a new page/route for people to create a discussion
- a user shall be able to type into a text area and click on a submit button
- after clicking the submit button, it should redirect them to a discussion/:slug page
- clicking on the "Start a Discussion" button should navigate the user to this create discussion page

### Notes
Since we don't have an API, there is no need to implement any real logic other than maybe using a useState hook to keep track of what the user typed.

This button should do something:
![Screen Shot 2021-04-03 at 8 39 39 PM](https://user-images.githubusercontent.com/1868782/113495070-b9637e80-94bc-11eb-9e33-f0ad22d5583d.png)

**Comment by mani-barathi** [comment]
@codyseibert I'll work on this
