### ISSUE TITLE
Create Article Page

### ISSUE THREAD

**Issue by codyseibert** [divanov11/Mumble#126]
There currently is no page for creating a new article.  We have a link called "Write a post", but it doesn't navigate the user to any usable page.  This feature would include the following work:

- create a new page/route for people to create a article
- a user shall be able to type into a text area and click on a submit button
- after clicking the submit button, it should redirect them to a article/:slug page
- clicking on the "Write a post" button should navigate the user to this create article page

### Notes
Since we don't have an API, there is no need to implement any real logic other than maybe using a useState hook to keep track of what the user typed.

![Screen Shot 2021-04-03 at 8 48 24 PM](https://user-images.githubusercontent.com/1868782/113495216-f0865f80-94bd-11eb-96ff-d0a52f0f60c6.png)

**Comment by ceelo777** [comment]
I'm interested in taking this issue!

**Comment by codyseibert** [comment]
@ceelo777 sounds good, remember to keep the page as basic as possible because it will more than likely be redesigned  away when Dennis finishes the API.  I'll checkback in a day or two to see if progress has been made.  Please remember to let us know if you decide to not work on this so I can't let someone else work on it! 

Thanks for your help!
