### ISSUE TITLE
Notifications Page

### ISSUE THREAD

**Issue by codyseibert** [divanov11/Mumble#128]
We have a link for All Notifications, but the page is empty.  We should probably have some basic list of placeholder notifications displayed on that page.

![Screen Shot 2021-04-03 at 8 55 38 PM](https://user-images.githubusercontent.com/1868782/113495328-f3358480-94be-11eb-8386-e48913666747.png)

**Comment by itzomen** [comment]
I want to be assigned to the task.
I'm getting started
