### ISSUE TITLE
Toggle Comment Button

### ISSUE THREAD

**Issue by codyseibert** [divanov11/Mumble#131]
The comment button should probably hide / show a comment textarea & button near the comment you are trying to reply to,

![Screen Shot 2021-04-03 at 9 04 36 PM](https://user-images.githubusercontent.com/1868782/113495499-35ab9100-94c0-11eb-855d-391ef5a5e27a.png)

**Comment by mani-barathi** [comment]
I'll take this one

**Comment by mani-barathi** [comment]
I'll move Post to its own component, right now Post related code is present directly in Feed and if I continue with that structure it will become a mess in future

**Comment by mani-barathi** [comment]
Is it not required right Now ? @divanov11 @codyseibert

**Comment by codyseibert** [comment]
@mani-barathi I'll have to ask, maybe Dennis didn't want a textarea to pop up when you click comment

**Comment by mani-barathi** [comment]
@codyseibert okie 👍

**Comment by codyseibert** [comment]
@mani-barathi we accidently closed the wrong issue, so you should be good to work on this one.  Sorry about that!

**Comment by codyseibert** [comment]
@mani-barathi be sure to pull master because I think I just changed that Feed component a bit

**Comment by mani-barathi** [comment]
@codyseibert okie!, I'll start on this one

**Comment by mani-barathi** [comment]
Is this okie? @codyseibert 

![image](https://user-images.githubusercontent.com/49336839/113499237-e4d48080-9531-11eb-9f9e-ff6171fdf7f1.png)

**Comment by codyseibert** [comment]
@mani-barathi looks fine to me!  good job!
