### ISSUE TITLE
Github Actions should fail on unformatted code PRs

### ISSUE THREAD

**Issue by codyseibert** [divanov11/Mumble#132]
People are still easily able to commit unformatted code.  I suggest we make the build fail if the CI/CD pipeline finds unformatted code in the PR.

This was also a recommendation from @eddiejaoude to help improve our review process.

**Comment by eddiejaoude** [comment]
Using Husky is convenient, it allows people to be aware of an issues before committing (using `pre-commit` hook), however, this can be skipped/bypassed, so a GitHub Action (CI) to check this independently is still required. I highly recommend 👍 

Having automation check for smaller mistakes, allows the conversation of a PR to focus more on the important items 🤓

**Comment by codyseibert** [comment]
I'm going to see if I can grab this one

**Comment by Vyvy-vi** [comment]
I think #135 closes this issue
