### ISSUE TITLE
There is a package lock and a  yarn lock?

### ISSUE THREAD

**Issue by eddiejaoude** [divanov11/Mumble#133]
**Preflight Checklist**

* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Describe the bug**

Multiple lock files does not seem right

**To Reproduce**

**Expected behavior**

**Add additional instructions and considerations for the assignee**
- [ ] Jupiter
- [ ] Saturn
- [ ] Neptune

**Screenshots**

**Additional context**

Add any other context about the problem here (include commit numbers and branches if relevant)

**Comment by codyseibert** [comment]
I think we don't have any hard requirements for is someone can use yarn or npm to install deps.  Do you think there is an issue having both @eddiejaoude ?

**Comment by eddiejaoude** [comment]
Yep, unfortunately having both, they will get out of sync and cause weird issues. I would pick style and have everyone use that 🤓

**Comment by Mr-spShuvo** [comment]
> Yep, unfortunately having both, they will get out of sync and cause weird issues. I would pick style and have everyone use that 🤓

Agree with @eddiejaoude. Even yarn complains about it. Will add `yarn.lock` into `.gitignore`

**Comment by Mr-spShuvo** [comment]
Resolved with [this commit](https://github.com/divanov11/Mumble/commit/e5cfa12e6a3b59cfbd12f9dc10c3ac185003c843)
