### ISSUE TITLE
Dependencies list in the README

### ISSUE THREAD

**Issue by martin-99** [divanov11/Mumble#14]
Hi, I think we should add a dependencies list in the README file for future contributors.

**Comment by divanov11** [comment]
Yes :)

**Comment by Mr-spShuvo** [comment]
Closing this as putting dependencies list in readme is not a good idea as it's constantly changes.
If you want to learn about dependencies, you can look up on `package.json` file
or on the [dependencies graph](https://github.com/divanov11/Mumble/network/dependencies)  https://github.com/divanov11/Mumble/network/dependencies
