### ISSUE TITLE
TypeError: Cannot read property 'skills' of undefined

### ISSUE THREAD

**Issue by itzomen** [divanov11/Mumble#143]
**Preflight Checklist**

* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Describe the bug**

When clicked on the notification dropdown " Started following you ", it outputs the error "TypeError: Cannot read property 'skills' of undefined"

**To Reproduce**

1. Go to 'Home'
2. Click on 'Notofication'
3. Then click on 'Sulamita Ivanov Started following you'
4. See error, "TypeError: Cannot read property 'skills' of undefined

**Expected behavior**

This is supposed to take you to that user's profile page

**Comment by Mr-spShuvo** [comment]
Resolved with [this commit](https://github.com/divanov11/Mumble/commit/dddcbd4879dca39e8bc4e7d7ede9bbefd19d492c)

**Comment by itzomen** [comment]
Alright great
