### ISSUE TITLE
Settings page not well styled

### ISSUE THREAD

**Issue by itzomen** [divanov11/Mumble#144]
**Preflight Checklist**

* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Describe the bug**

The settings page is not styled as it is supposed to be

**To Reproduce**

1. Go to 'Home'
2. Click on Profile 'Dropdown'
3. And Select 'Settings'

**Screenshots**
![settings](https://user-images.githubusercontent.com/61752841/113505121-cae86d00-9534-11eb-9216-df5561b939e8.png)

**Comment by codyseibert** [comment]
@itzomen how is it supposed to be styled?  Is there a design screenshot?

**Comment by itzomen** [comment]
> @itzomen how is it supposed to be styled? Is there a design screenshot?

![Screenshot from 2021-04-04 17-41-26](https://user-images.githubusercontent.com/61752841/113515548-128aeb00-956d-11eb-8e84-9d21c939e700.png)
The two components/containers should be contained as seen in the Profile page

**Comment by divanov11** [comment]
I think I’m actually fine with how it is now ;)

**Comment by codyseibert** [comment]
@itzomen hey thanks for making this issue, but since @divanov11 says he is ok with the current styling, I'm going to go ahead and close this issue.
