### ISSUE TITLE
There is no space between the icon and the name in the dropdown menu

### ISSUE THREAD

**Issue by MidouWebDev** [divanov11/Mumble#145]
In the dropdown menu we have icons + name directly without any space which makes it look bad !

![Screenshot_20210404-110416_Samsung Internet](https://user-images.githubusercontent.com/72341453/113505317-dd16db00-9535-11eb-8419-2c3dda2d559a.jpg)

**Comment by codyseibert** [comment]
This seems like it was fixed at some point.

![Screen Shot 2021-04-04 at 2 18 19 PM](https://user-images.githubusercontent.com/1868782/113517878-9e424e80-9550-11eb-822e-5ee39fa33238.png)

**Comment by MidouWebDev** [comment]
@codyseibert thanks i have just noticed that and was going to close it
