### ISSUE TITLE
Upvote Number missing on Discussion Page

### ISSUE THREAD

**Issue by codyseibert** [divanov11/Mumble#156]
Something must have went wrong at some point, because there is no upvote number on the discussion page as you can see in the screenshot.

![Screen Shot 2021-04-05 at 1 23 14 AM](https://user-images.githubusercontent.com/1868782/113540160-80ef9d80-95ad-11eb-8961-e91a0f7d84ba.png)

**Comment by mani-barathi** [comment]
I'll fix it
