### ISSUE TITLE
Text in the search bar and Search by options are not visible in dark mode

### ISSUE THREAD

**Issue by bharathjinka09** [divanov11/Mumble#161]
**Describe the bug**

Text in the search bar and Search by options are not visible in dark mode
In Search by options right side, the options are not visible in dark mode

**To Reproduce**

1. Go to 'Search bar and type, then the text won't visible'
1. It is in a dark color. It should be in white or any lighter color.

**Screenshots**

![Screenshot from 2021-04-05 16-49-39](https://user-images.githubusercontent.com/33654188/113573507-e2f4e500-9637-11eb-8442-2cdac5ec0a0a.png)

![Screenshot from 2021-04-05 17-55-11](https://user-images.githubusercontent.com/33654188/113573603-1899ce00-9638-11eb-816c-ab0c0e66cc9f.png)

Thanks

**Comment by codyseibert** [comment]
Nice catch! Thanks for adding this issue

**Comment by Mr-spShuvo** [comment]
Resolve with [this commit ](https://github.com/divanov11/Mumble/commit/9f898654ac41bc037cc4a0c429e86ed0fbc013bf)
