### ISSUE TITLE
There is no space between the icon and the name in the dropdown menu (mobile view)

### ISSUE THREAD

**Issue by MidouWebDev** [divanov11/Mumble#162]
![Screenshot_20210405-150638_Samsung Internet.jpg](https://user-images.githubusercontent.com/72341453/113582768-b2558100-9620-11eb-9307-8b9cbb7dee13.jpg)

**Comment by Hrithik5** [comment]
This issue is solved right! we should close this issue?

**Comment by codyseibert** [comment]
@Hrithik5 this is still an issue on iPhone chrome mobile

**Comment by TysonThurman** [comment]
I would like to work on this fix if possible.

**Comment by TysonThurman** [comment]
I submitted the PR above to resolve the issue with the spacing. This is my first one but I don't think I missed anything while following the contribution guidelines. Please let me know if I did.

**Comment by MidouWebDev** [comment]
Great work tyson !
