### ISSUE TITLE
Dark Mode not enabled in the third column 

### ISSUE THREAD

**Issue by MidouWebDev** [divanov11/Mumble#163]
As you can see in the screenshot, the third column doesn't have the same background color as the first and second one.
The third column should have the same bg color in the dark mode :

![image](https://user-images.githubusercontent.com/72341453/113586012-e16df180-9624-11eb-874f-c7cabf045c64.png)

**Comment by Mr-spShuvo** [comment]
Resolve with [this commit ](https://github.com/divanov11/Mumble/commit/9f898654ac41bc037cc4a0c429e86ed0fbc013bf)
