### ISSUE TITLE
There is no space between the icon and the name in the notifications dropdown menu

### ISSUE THREAD

**Issue by MidouWebDev** [divanov11/Mumble#180]
![Screenshot_20210406-211358_Samsung Internet](https://user-images.githubusercontent.com/72341453/113773058-676d6380-971d-11eb-8f26-2fb7aac6b05c.jpg)

**Comment by mani-barathi** [comment]
I think this issue has been fixed.  check the changes and close the issue.

**Comment by TysonThurman** [comment]
I do still see the issue on iPhone

**Comment by MidouWebDev** [comment]
@mani-barathi try it on a mobile device

**Comment by Rashik4567** [comment]
@MidouWebDev  its fixed... 
![image](https://user-images.githubusercontent.com/58215479/113826018-7d256c00-97a3-11eb-8f56-b582937d3f58.png)

**Comment by Rashik4567** [comment]
in iphone x

**Comment by mani-barathi** [comment]
> @mani-barathi try it on a mobile device

Everything seems fine on my devices.

**Comment by MidouWebDev** [comment]
Still not fixed in an android device !
