### ISSUE TITLE
The "Follow" Button doesn't have the same position 

### ISSUE THREAD

**Issue by MidouWebDev** [divanov11/Mumble#191]
The "Follow" Button doesn't have the same position !!

![image](https://user-images.githubusercontent.com/72341453/113918032-da3c1480-97d9-11eb-8082-2a4394d0d23a.png)

**Comment by mani-barathi** [comment]
I'll fix this

**Comment by MidouWebDev** [comment]
@codyseibert @Mr-spShuvo 
There is a PR created by @mani-barathi that solves this issue 
Please check it !
