### ISSUE TITLE
In profile page after clicking comment it is going to home page

### ISSUE THREAD

**Issue by bharathjinka09** [divanov11/Mumble#199]
On the profile page, after clicking the comment it is going to the home page.

Actual behavior is, it should display a comment box to comment.

Thanks

**Comment by BrundaBR** [comment]
@bharathjinka09  i am working on it ,Thank you

**Comment by hamzalak** [comment]
https://github.com/divanov11/Mumble/pull/205

**Comment by BrundaBR** [comment]
@hamzalak  is it done?

**Comment by hamzalak** [comment]
@BrundaBR

**Comment by bharathjinka09** [comment]
👍
