### ISSUE TITLE
dark mode & light mode features

### ISSUE THREAD

**Issue by vinzvinci** [divanov11/Mumble#21]
**Description:**
It will be cool if the website has dark and light mode features. 

**Is this really important?:**
Yeah, it hurts seeing light mode `(I'm sure other people recommend dark mode too)`

**Comment by vinzvinci** [comment]
Thanks for a great feedback! We can keep this issue open while `dark mode feature` isn't release.

**Comment by EugeneGohh** [comment]
> This will be one of the final steps before MVP launch. I agree, nowdays its almost expected ;)

Hi there, I have worked on this issue. Here's the [PR](https://github.com/divanov11/Mumble/pull/42), feel free to make some changes to it.

**Comment by divanov11** [comment]
Yea I think we can put this on hold for now. We’ll end up having to redo a lot if we implement it before the core design

**Comment by Mr-spShuvo** [comment]
I will work on this.

**Comment by Mr-spShuvo** [comment]
Added with [this commit](https://github.com/divanov11/Mumble/commit/3266f955c854db5098e57ebb09298c8f8608b73b)
