### ISSUE TITLE
Adding Placeholder Logout Button Functionality

### ISSUE THREAD

**Issue by codyseibert** [divanov11/Mumble#214]
Clicking on the logout button should probably fire a redux action / reducer so that we can clear the stored user information in the future and redirect the user to the login page.  This work involves making some redux actions which can be dispatched when clicking the logout button to redirect the user to the login page.

![Screen Shot 2021-04-09 at 9 12 42 AM](https://user-images.githubusercontent.com/1868782/114185448-bed52480-9913-11eb-9fdd-d1bc15b2113b.png)

**Comment by mani-barathi** [comment]
I'll take this one
