### ISSUE TITLE
Fixing Odd Avatar Notification Loading

### ISSUE THREAD

**Issue by codyseibert** [divanov11/Mumble#217]
When loading the application for the first time (and on a slower network), the avatars in the notification dropdown are oval-shaped until the image finishes loading.  See attached gif:

![Apr-09-2021 09-19-08](https://user-images.githubusercontent.com/1868782/114186388-c648fd80-9914-11eb-8a1d-0035fc3c36b7.gif)

You may need to throttle your network after loading the page to get this to reproduce depending on how fast your internet is.  Also disable your cache so it doesn't re-load images from disk.

![Screen Shot 2021-04-09 at 9 21 04 AM](https://user-images.githubusercontent.com/1868782/114186484-ebd60700-9914-11eb-8993-bf77a9d1be7f.png)

**Comment by itzomen** [comment]
Is that not normal behaviour when loading media?
Or what is a possible approach to fix that because I will like to fix that.

**Comment by codyseibert** [comment]
@itzomen I think it could be fixed with a fixed width height avatar.  I'm not sure what's going on here, but I'll assign it to you!

**Comment by codyseibert** [comment]
@itzomen i noticed the space between the avatar and the text is gone now, did you want to try and fix that?

**Comment by itzomen** [comment]
Oh I see, yeah I will fix that
![notif](https://user-images.githubusercontent.com/61752841/114279087-bf141380-9a2a-11eb-9104-768dc3f9a9c2.png)

Also thought of reducing the font size so the notification title fit in two lines as shown on the attached pic

**Comment by codyseibert** [comment]
Yeah that's probably fine

**Comment by codyseibert** [comment]
I think this is fixed
