### ISSUE TITLE
Hovering over some links don't change any styles

### ISSUE THREAD

**Issue by codyseibert** [divanov11/Mumble#218]
When hovering over the discussions panels links (and probably other places in the app), there is no underline or any change in link color.  It is harder for a user to know this is a link without also adding another form of feedback other than a pointer cursor.

Look through the app and find any buttons or links that are clickable but don't change styles and fix.

![Apr-09-2021 09-23-02](https://user-images.githubusercontent.com/1868782/114186904-63a43180-9915-11eb-948c-e5644b110fdd.gif)

**Comment by Rashik4567** [comment]
Please check request #298

**Comment by codyseibert** [comment]
I'll close this for now, but there are still a lot of links that don't show any hover feedback.  I think we need to make a shared component or a common BEM class for links and use that.

**Comment by MidouWebDev** [comment]
#306 closes this issue !
Now all the links have a underline decoration 👍🏼
