### ISSUE TITLE
Add ISSUE_TEMPLATES

### ISSUE THREAD

**Issue by vinzvinci** [divanov11/Mumble#22]
**Description:**
I recommend add **ISSUES_TEMPLATES** with **label**. 

Like
- Feature request
- Bug
- Etc.

~~-~~

**Is this really important?:**
Yes, this can be use as a guide specially when there's new people in **open-source** and wants to contribute in this repo.

**Comment by divanov11** [comment]
Agreed

**Comment by abhivemp** [comment]
I am down to work on this. Just want to confirm with you both @divanov11 @vinzvinci since there is no task assigning in this repo.

**Comment by Vyvy-vi** [comment]
We could maybe grab some of the pre-existing templates, if Dennis agrees on them:
https://github.com/stevemao/github-issue-templates/

The added benefit of these is automatic label assignment when an issue of a certain type is opened. (*the labels would have to be created, before being they can be assigned) https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

Github gives a neat UI to select type of issues, when someone's making a new issue.
### Screenshot:
![Screenshot 2021-03-31 at 1 35 15 AM](https://user-images.githubusercontent.com/62864373/113049525-5ecad980-91c1-11eb-8c13-279c964afddd.png)

**Comment by abhivemp** [comment]
@Vyvy-vi I guess I should've been specific but yes, I agree with you in that we should take templates. Ultimately, Dennis should make the call.

**Comment by abhivemp** [comment]
Think we can close this issue?

**Comment by Vyvy-vi** [comment]
Hmm, it can be closed.
btw @abhivemp GitHub automatically closes issues when associated PRs are merged, if you add-
`closes #<issue-number>` in the pull request message, or in a commit message description

Either of these, followed by an issue-number mention works:
`closes, fixes, resolves`

**Comment by Vyvy-vi** [comment]
*Oh wait a min.
The PR has an issue-
The issue templates should be in a folder titled`ISSUE_TEMPLATE` inside `.github`, instead of `ISSUE_TEMPLATES`, for GitHub to pick those up and render them when someone opens an issue.

**Comment by abhivemp** [comment]
yea that was me. I am actually drafting another PR. I am going to fix it now.
