### ISSUE TITLE
Fix CSS to be BEM

### ISSUE THREAD

**Issue by codyseibert** [divanov11/Mumble#220]
A lot of the CSS isn't proper BEM from what I could tell.  This issue is to run through all our css and verify we follow BEM.

**Comment by itzomen** [comment]
Sounds good to me 😃

**Comment by itzomen** [comment]
@codyseibert I have gone through the CSS files and seems good to me

**Comment by codyseibert** [comment]
Ok let me double check.  Did you paste them into a BEM validation site such as https://torleif.nz/bem/ ?

**Comment by codyseibert** [comment]
![Screen Shot 2021-04-12 at 5 19 54 PM](https://user-images.githubusercontent.com/1868782/114464107-4db39c80-9bb3-11eb-8db2-fd429b412bb7.png)

there are tons of BEM validation errors in all the CSS.  Take any css file and put it into an online BEM validator and it'll show the errors.

**Comment by itzomen** [comment]
Yeah, i noticed.. thanks for the feedback.
I will be fixing that asap.

**Comment by itzomen** [comment]
> Yeah, I noticed.. thanks for the feedback.
> I will be fixing that asap.
Oh, My My, I tried fixing the CSS to BEM but almost all the CSS files have issues and I'm not really comfortable with frontend.

**Comment by itzomen** [comment]
> Yeah, i noticed.. thanks for the feedback.
> I will be fixing that asap.

Oh, My My, I tried fixing the CSS to BEM but almost all the CSS files have issues and I'm not really comfortable with frontend.

**Comment by codyseibert** [comment]
> > Yeah, i noticed.. thanks for the feedback.
> 
> > I will be fixing that asap.
> 
> 
> 
> Oh, My My, I tried fixing the CSS to BEM but almost all the CSS files have issues and I'm not really comfortable with frontend.

No worries, maybe I can get to this soon

**Comment by codyseibert** [comment]
I fix a lot of the issues, but there are still some css files not properly doing BEM

**Comment by MidouWebDev** [comment]
> I fix a lot of the issues, but there are still some css files not properly doing BEM

Do we still have css files that don't support the BEM ?

**Comment by codyseibert** [comment]
@MidouWebDev I'll try to look through them and maybe close this card if everything looks good

**Comment by codyseibert** [comment]
I just checked, there is still css failing bem validation

**Comment by MidouWebDev** [comment]
@codyseibert Can you share the files link ?
So that i can fix that issue
