### ISSUE TITLE
Text doesn't appear in Dark Mode (create-article)

### ISSUE THREAD

**Issue by MidouWebDev** [divanov11/Mumble#230]
In the light mode, everything is okay : we can see the text that we are typing 
---> Preview :
![20210410_182055](https://user-images.githubusercontent.com/72341453/114278953-ff26c680-9a29-11eb-9829-6ba4d3d73740.jpg)

But in the dark mode, we can't see the text that we are typing until we select it !
---> Preview without selecting the text :
![20210410_182840](https://user-images.githubusercontent.com/72341453/114279064-9f7ceb00-9a2a-11eb-83b7-1451ba64504e.jpg)

---> Preview when we select the text we are typing :
![20210410_182118](https://user-images.githubusercontent.com/72341453/114278966-22517600-9a2a-11eb-91d3-39899589681f.jpg)

**Comment by codyseibert** [comment]
Nice find!
