### ISSUE TITLE
Results are shown after a "No results found" msg

### ISSUE THREAD

**Issue by MidouWebDev** [divanov11/Mumble#232]
when clicking on view more i have an error msg : NO RESULTS FOUND
then the results are shown
Here is a gif :

 
![screen-capture](https://user-images.githubusercontent.com/72341453/114281368-ec19f380-9a35-11eb-9b74-614505cf486a.gif)

**Comment by codyseibert** [comment]
I think we need to add some placeholder elements while it tries to fetch the posts.  This is due to the network request taking some time.

**Comment by mani-barathi** [comment]
I'll do this
