### ISSUE TITLE
Not Found page

### ISSUE THREAD

**Issue by mhhabib** [divanov11/Mumble#254]
Want to work on **search mumble** not found page

**Comment by MidouWebDev** [comment]
The 404 page ?
I also wanna work on it 
I have imagined a 404 page for mumble !

**Comment by mhhabib** [comment]
@MidouWebDev kind of 404 pages. Currently searching a mumble shows a simple **No Results found..**. Can be designed a better page

**Comment by MidouWebDev** [comment]
@mhhabib DM me on Discord, i am the server admin (Mehdi <MidouWebDev/> #9105)
