### ISSUE TITLE
Delete post tool tip

### ISSUE THREAD

**Issue by divanov11** [divanov11/Mumble#255]
We need a tool tip that pops up so users can delete and edit their posts. For now if someone wants to create the layout and pop up , I will add in the functionality to the API.
![tooltip](https://user-images.githubusercontent.com/33843378/114600749-4d221100-9c5a-11eb-9c35-223a34815d82.PNG)

**Comment by mohammad4kh** [comment]
@divanov11 I tried to make the layout, this what I got so far

this menu will show if the user is not the author of the post
![hide](https://user-images.githubusercontent.com/6501582/114775712-e7c14380-9d71-11eb-9f19-27f8c9efc168.gif)

and this will show to the author of the post
![edit_delete](https://user-images.githubusercontent.com/6501582/114775808-032c4e80-9d72-11eb-9034-3da82add9c55.gif)

What do you think ?

**Comment by mohammad4kh** [comment]
Updated version for other users post menu

![image](https://user-images.githubusercontent.com/6501582/114785426-f6f9be80-9d7c-11eb-83f4-72d77539f2b2.png)

**Comment by divanov11** [comment]
Looks great!! I will merge in a bit. Just added the re-mumble functionality so I will be testing that before adding user registration.
