### ISSUE TITLE
Write Article button is not there in the home page

### ISSUE THREAD

**Issue by bharathjinka09** [divanov11/Mumble#264]
Hi all,
**Describe the bug**

Previously write article button was there on the home page. But now it is not there. Is there any reason to remove the button? Please check. 

Thanks.

**Comment by divanov11** [comment]
I removed it for now. I’ll find another place for it, through the “make a post” section should be a bit more condensed.

**Comment by bharathjinka09** [comment]
Yeah. Nice idea
