### ISSUE TITLE
Internal server error (code 500) on mumble.dev

### ISSUE THREAD

**Issue by Rashik4567** [divanov11/Mumble#272]
**Preflight Checklist**

* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Describe the bug**

```Error: Cannot read property 'map' of undefined```
Its an internal server error (code 500) on mumble.dev . the site loads first and then the error occures. But on incognito, it doesn't.

![Annotation 2021-04-16 163101](https://user-images.githubusercontent.com/58215479/115012045-291c3500-9ed1-11eb-83dc-4d04a4d841ed.png)
 

**To Reproduce**

1. Go to https://www.mumble.dev/ ( in chrome )
2. See error

**Expected behavior**

User registration and login system is causing the error ( because i tried in in incognito then it was file with the dummy account )

**Comment by MidouWebDev** [comment]
it is working now i guess

**Comment by codyseibert** [comment]
@Rashik4567 can you check if this is still an issue?  I can't reproduce.

**Comment by Rashik4567** [comment]
Ok, this issue is fixed.
