### ISSUE TITLE
Theme changer in settings is not done properly.

### ISSUE THREAD

**Issue by Rashik4567** [divanov11/Mumble#286]
**Preflight Checklist**

* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Describe the bug**

The theme changer toggle does not have any title. 
![theme](https://user-images.githubusercontent.com/58215479/115136736-98199b00-a043-11eb-84b2-7dc225e071c0.png)

**To Reproduce**

1. Go to 'mumble.dev'
2. Click on 'profile icon on navbar'
3. Click on 'settings'
4. See the last row of the middle section

**Comment by MidouWebDev** [comment]
Merged
