### ISSUE TITLE
Continuous Hierarchy Of Reply

### ISSUE THREAD

**Issue by jewells07** [divanov11/Mumble#308]
**It's having Continuous Hierarchy Of Replies. We have to stop at once.**

![comments](https://user-images.githubusercontent.com/54440548/115946002-13fc6300-a4dc-11eb-9402-6aaf8e862c11.png)

**Comment by codyseibert** [comment]
I'm not sure what you mean.  Having nested comments is currently the design we want as of right now.

**Comment by jewells07** [comment]
Isn't weird to keep nesting? instead we use "@username"

**Comment by jewells07** [comment]
Yes got it. Let's keep it for the future if we want to redesign.

**Comment by MidouWebDev** [comment]
@codyseibert 
@jewells07 

so i guess we should close the issue !

**Comment by codyseibert** [comment]
I'm going to close this issue.  I think we will continue to go with out current comment approach until we start to see major issues on real data.
