### ISSUE TITLE
Follow user from profile

### ISSUE THREAD

**Issue by divanov11** [divanov11/Mumble#312]
We should add a follow button to users profile. At this point we can only follow users from the search page or "recommended users" card.

![Follow Button](https://user-images.githubusercontent.com/33843378/116140469-fcb8a380-a69c-11eb-90cb-7b0bb94b9fac.PNG)

![Follow Button 2](https://user-images.githubusercontent.com/33843378/116140531-12c66400-a69d-11eb-9ede-b72584908006.PNG)

**Comment by MidouWebDev** [comment]
I think i am going to work on it

**Comment by MidouWebDev** [comment]
@divanov11 i worked on it but it is showing an error
You can check my PR #318 

![image](https://user-images.githubusercontent.com/72341453/116239519-4616fa80-a752-11eb-9070-4cb574ea8d18.png)
