### ISSUE TITLE
Back button/Redirecting issue on Profile endpoint

### ISSUE THREAD

**Issue by jewells07** [divanov11/Mumble#315]
Clicking on the profile it will **redirect to the same page (we can't notice because we already on that page)**,
but when we want to go back we have to click back as much as we clicked on the profile

Example : Clicked 3 times on profile, no effect because we already on that page. If we want to go back we have to click 3 times too.

**NOTE: Referring browser back button, Not the "GO BACK" button on page**

![profilebug](https://user-images.githubusercontent.com/54440548/116183452-8028d200-a73b-11eb-9762-3987e8e7b3e5.jpg)

**Comment by MidouWebDev** [comment]
Can you explain it using the template ?
I didn't get the point

**Comment by jewells07** [comment]
We are knowing that, But as a user we go back with browser button. In mobile also we go back with back button.

![Inkedbackbtnjpg](https://user-images.githubusercontent.com/54440548/116260955-cd855d80-a794-11eb-989a-dce6729b7028.jpg)

**Comment by codyseibert** [comment]
This is the default behavior of links on websites.  Go to any website and click on a link that navigates you to the same page multiple times, you'll notice you have to click the back button multiple times.

**Comment by codyseibert** [comment]
I fixed this in the following commit: https://github.com/divanov11/Mumble/commit/33628ae2639e260481bfafda049da5c9030ac6cf
