### ISSUE TITLE
Go Home link not updating the page on 500 ( Internal Server Error ! ) page

### ISSUE THREAD

**Issue by thisisganesh** [divanov11/Mumble#319]
**Preflight Checklist**

* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Describe the bug**

On the 500 error page, if we click on the go-home link it is just updating the link in the browser but not the page. 

**To Reproduce**

1. login into mumble
2. Click on any topic in the Discussions section
3. on 500 error page, click on the go-home link
4. See an error

**Expected behavior**

It should update the page with home page content.

**Comment by Mr-spShuvo** [comment]
Resolved by [this commit](https://github.com/divanov11/Mumble/commit/abbb97a5ab8e5070fd77cddfdcd68f1a64f1bc18) 
![Uploading screenshot-localhost_3002-2021.04.28-03_08_42.png…]()

**Comment by thisisganesh** [comment]
https://www.mumble.dev/   . instead of showing landing page , it shows 500 page now.

**Comment by Mr-spShuvo** [comment]
That's because backend is broken.
