### ISSUE TITLE
Content not clearly visible in one of the theme mode ! 

### ISSUE THREAD

**Issue by PraveenMalethia** [divanov11/Mumble#322]
**Describe the bug**

**To Reproduce**

Just try to Switch between dark or light mode and then see the discussion card have green boxes with some content.

**Expected behavior**

The content between the green boxes of the Discussion card must be soft to the eyes or I mean they should be clearly visible, the user should not have to struggle reading the content of green boxes.

**Screenshots**
![image](https://user-images.githubusercontent.com/59171685/116324679-2cbb9000-a7de-11eb-9271-e029c2765c39.png)

**Comment by Mr-spShuvo** [comment]
This is visible. On which devices or browser?

![image](https://user-images.githubusercontent.com/22437186/116325443-fbde5980-a7e3-11eb-933c-0132cda4a6d7.png)

**Comment by PraveenMalethia** [comment]
There was an extention working in background ! Dark mode extention ! 
I Switched that off ! Now its good
