### ISSUE TITLE
site crashing due to bug in error dispatch actions

### ISSUE THREAD

**Issue by mani-barathi** [divanov11/Mumble#325]
Some states in the users and posts reducer are failing when there is a server error(500) as we are dispatching error to state, but we are not setting the arrays to empty arrays. And in the components we are trying to map over the arrays which are not defined

**To Reproduce**
- this happens only if there is an internal server error

![image](https://user-images.githubusercontent.com/49336839/116345307-82eff980-a805-11eb-8d50-2acc2241a110.png)

**Solution**
- either we can set empty arrays when we are dispatching errors in reducers
- or we can check for errors before mapping over the arrays in the components

**Comment by gmrzone** [comment]
There is no Database in Backend server

**Comment by mani-barathi** [comment]
Ohh Okie... but still I think it needs to be fixed.
