### ISSUE TITLE
A mail template for Email verification

### ISSUE THREAD

**Issue by PraveenMalethia** [divanov11/Mumble#331]
A clear and concise description of what you want to happen is to create a mail template for email verification 

**Describe alternatives you've considered**

I have come to an idea to get an HTML template with all CSS styling and some buttons and URL too

**Add additional instructions and considerations for the assignee**
- [x ] Html and CSS only! no react
So i can integrate it with backend and backend will send this template to email with dynamic data and token for verification

**Additional context**

![image](https://user-images.githubusercontent.com/59171685/116515906-8b6e3000-a8ea-11eb-91e8-de4708f4b2eb.png)

Here is the reference to that template!

**Comment by MidouWebDev** [comment]
In which folder can i add this new file that i will create ? @PraveenMalethia

**Comment by PraveenMalethia** [comment]
In users create a folder name templates . 
And paste it there

**Comment by MidouWebDev** [comment]
Mobile view :

![mumble-email-mobile](https://user-images.githubusercontent.com/72341453/116545244-b3a46180-a8df-11eb-8786-79891d3989b9.png)

Laptop :

![mumble-email](https://user-images.githubusercontent.com/72341453/116545269-b99a4280-a8df-11eb-966f-eeac07ec44d2.png)
