### ISSUE TITLE
Request failed with status code 500 (login)

### ISSUE THREAD

**Issue by MidouWebDev** [divanov11/Mumble#334]
**Preflight Checklist**

* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Describe the bug**

I can't login

**To Reproduce**

1. Go to 'mumble.dev'
2. Type the username and password
3. Login
4. See error : Request failed with status code 500

**Comment by MidouWebDev** [comment]
![Uploading image.png…]()

**Comment by MidouWebDev** [comment]
![image](https://user-images.githubusercontent.com/72341453/116791100-9cb06b80-aaa7-11eb-92e6-8eda3e6efa5c.png)

**Comment by PraveenMalethia** [comment]
The backend still needs to be fixed! the database is empty and @divanov11  will create that dummy user, after that you will be able to login!
