### ISSUE TITLE
FEAT: Topic Search Page

### ISSUE THREAD

**Issue by i-am-zach** [divanov11/Mumble#34]
Taken from TASKS-UPDATES.md:

Topic search page - Search topics and add them to your list of interests

**Comment by i-am-zach** [comment]
I'm not taking this one, but thought it should be raised as an issue so someone can!

**Comment by codyseibert** [comment]
Some work was done on this with #59

**Comment by codyseibert** [comment]
@divanov11 is already working on this / almost finished with it
