### ISSUE TITLE
Notifications Dropdown should have a fixed height and scrollbar.

### ISSUE THREAD

**Issue by codyseibert** [divanov11/Mumble#341]
as you can see in the image, when there are too many notifications, they go off the screen.  Either put these in a fixed height scroll bar, or only display the most recent 3 and display a "see 20 more notifications" link that will redirect them to their notification page.

![Screen Shot 2021-05-08 at 10 30 50 AM](https://user-images.githubusercontent.com/1868782/117542878-78451980-afe8-11eb-8f84-4eef71a5422c.png)

**Comment by mani-barathi** [comment]
@codyseibert Does this look ok?

![asdf](https://user-images.githubusercontent.com/49336839/117611651-7f535f80-b181-11eb-9d41-d04a98fdec04.gif)

**Comment by codyseibert** [comment]
@mani-barathi I think so, make a PR, thanks!

**Comment by MidouWebDev** [comment]
@codyseibert you forgot adding the issue to the Project Board !!
