### ISSUE TITLE
Can't type in the input in ForgotPassword

### ISSUE THREAD

**Issue by MidouWebDev** [divanov11/Mumble#342]
### Preflight Checklist

* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

#

### Describe the bug

Can't type in the input in ForgotPassword.js 

#

### To Reproduce

1. Go to 'https://www.mumble.dev/forgot-password'
2. Click on 'email address (input)'
3. Type anything
4. See the error

#

### Expected behavior

I expected to have the ability to type on

**Comment by mani-barathi** [comment]
I'll fix this right now

**Comment by MidouWebDev** [comment]
#343
