### ISSUE TITLE
A bug in Top Contributors Column

### ISSUE THREAD

**Issue by MidouWebDev** [divanov11/Mumble#344]
### Preflight Checklist

* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

#

### Describe the bug

Top Contributors column has an inappropriate length

#

### To Reproduce

1. Go to 'mumble.dev'
2. Login
3. See Error

#

### Screenshots

![image](https://user-images.githubusercontent.com/72341453/117639859-e66a1780-b173-11eb-93c3-b2735020d61a.png)

**Comment by PraveenMalethia** [comment]
![image](https://user-images.githubusercontent.com/59171685/117646280-344d4280-b1a9-11eb-8696-3a7b0b7fa821.png)

the issue is when we resize the screen from large to small!

**Comment by Mr-spShuvo** [comment]
Don't worry about it now, A sidebar navigation will go there. And Top contributor section be on the right hand side eventually.
This is not a bug this is a feature, lol. 😉

**Comment by MidouWebDev** [comment]
@Mr-spShuvo i didn't know about the sidebar feature !
That's why i thought that it is a bug

**Comment by Mr-spShuvo** [comment]
Don't worry about it. You did a good job. I fixed the layout. Let's check out.
