### ISSUE TITLE
Scrolling and hidden card

### ISSUE THREAD

**Issue by jewells07** [divanov11/Mumble#349]
One of them is **scrolling** and another is **sticky**

![scroll1](https://user-images.githubusercontent.com/54440548/117758852-5fcf3c00-b240-11eb-9595-e0f15ef954f2.jpg)

The **sticky** one hide the "skill tag" card.

![scroll2](https://user-images.githubusercontent.com/54440548/117758958-9311cb00-b240-11eb-87fb-618bb26ad69b.jpg)

**Comment by Mr-spShuvo** [comment]
The first one is expected.
The second one, what is the device resolution can you tell me?

**Comment by S-Rosemond** [comment]
<div style={{ position: 'fixed' }}>
          <TopicTags tags={user.interests} />
          <DiscussionsCard discussions={discussions} />
        </div>

Solution: src/pages/HomePage.js needs a div with a fixed position as a wrapper for the two cards.
