### ISSUE TITLE
FEAT: Article Page

### ISSUE THREAD

**Issue by i-am-zach** [divanov11/Mumble#35]
Standalone page for an article. The page that should render when someone goes to `http://mumble.dev/articles/<slug>`. Should be implemented in the frontend folder.

Note to Dennis (and other Repository Managers): you can assign users to issues to that it's clear to everyone that they are responsible for appropriate task. Read about it here https://docs.github.com/en/enterprise-server@2.22/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users

I'm not taking this issue so whoever wants to take it should comment and Dennis can assign it to you.

**Comment by abisalde** [comment]
Hi Zach,

I want to take the issue for the Article page. However, do we have a mock-up, or I just come up with something on my own because I am more of building with a mock-up design.

Do let me and I await your feedback

**Comment by i-am-zach** [comment]
@abisalde ask the design team in the discord if they have anything

**Comment by divanov11** [comment]
I’m working on the design now

**Comment by abisalde** [comment]
That's great! @divanov11 

I will be looking forward to turn the design into code.

**Comment by codyseibert** [comment]
@divanov11 says he plans to work on the design and implement it
