### ISSUE TITLE
Add a Loading indicator on register

### ISSUE THREAD

**Issue by Parkar99** [divanov11/Mumble#351]
I clicked register multiple times due to no visual indicator that there was a request ongoing

Solution:

Some kind of loading indicator that the account register is ongoing before it's redirected to the home page

**Comment by okumujustine** [comment]
Who is working on this, I can fix it up if not?

**Comment by okumujustine** [comment]
I added a PR for this up there, checks if a user is logged in and the current profile's username is not equaled to the logged-in username. Since the username is unique, this should provide a solution. 

Hopefully, this works out..

**Comment by MidouWebDev** [comment]
Assigned to @okumujustine
