### ISSUE TITLE
You're able to follow yourself

### ISSUE THREAD

**Issue by Parkar99** [divanov11/Mumble#352]
### Preflight Checklist

* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

#

### Describe the bug

A user is able to follow themselves

#

### To Reproduce

1. Click on your profile
2. Follow button appears which is clickable

#

### Expected behavior

No follow button should appear since it's your own profile

**Comment by abhivemp** [comment]
@codyseibert I Think this is a bug for the backend?

**Comment by Parkar99** [comment]
@abhivemp Also front end since it shouldn't show in UI

**Comment by codyseibert** [comment]
@abhivemp @Parkar99 There is logic in the backend that prevents this from happening.  I think the frontend just needs to not change the button until we successfully know we followed the user

**Comment by codyseibert** [comment]
![Screen Shot 2021-05-12 at 9 14 55 PM](https://user-images.githubusercontent.com/1868782/118063447-1a595e80-b367-11eb-993a-57e13cde42a9.png)

**Comment by divanov11** [comment]
If someone wants to take care of this go ahead :) It's a nug but not a huge issue that we need to resolve before the launch of the MVP.

**Comment by okumujustine** [comment]
I added a PR for this up there, **it checks if a user is logged in and the current profile's username is not equaled to the logged-in username**. Since the username is unique, this should provide a solution. 

Hopefully, this works out.

**Comment by okumujustine** [comment]
this is what it looks like.

`          {isAuthenticated && userProfile?.username !== user?.username && (
            <div>
              <FollowButton userProfile={userProfile} />
            </div>
          )}`
