### ISSUE TITLE
Update Profile Avatar

### ISSUE THREAD

**Issue by MaxMohammadi** [divanov11/Mumble#353]
### Preflight Checklist

* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

#

### Describe the bug

Updating personal avatar reports error "Endpoint Currently Not available"

#

### To Reproduce

1. Go to Settings
2. Click on Update Avatar
3. Upload file

#

### Expected behavior

The profile picture state should change from default to newly uploaded file

**Comment by codyseibert** [comment]
I'll work on this one

**Comment by MidouWebDev** [comment]
#360
