### ISSUE TITLE
Registration form fails without a notification when username already exists

### ISSUE THREAD

**Issue by codyseibert** [divanov11/Mumble#354]
### Describe the bug

Not user feedback when registering an account with an in-use username

### To Reproduce

1. Go to register
2. registare a user with a username
3. go back to register
4. enter the same username
5. notice no error displays on the UI saying "username is already taken"

**Comment by divanov11** [comment]
Looks like we need to simply return the error in an alert box. I'll take a quick look

**Comment by divanov11** [comment]
Ok so I just added an error message. We will need to customize what the response says in the backend. Currently we just get back an default status code. 
![Register Error](https://user-images.githubusercontent.com/33843378/118173189-3e667f80-b3fb-11eb-9838-910f0e65a38c.PNG)
