### ISSUE TITLE
Searching by User not working

### ISSUE THREAD

**Issue by codyseibert** [divanov11/Mumble#356]
Try searching by a known user in our system, and it won't come back on the search page.  I think it's related to the / appended to the search URL from the UI:

![Screen Shot 2021-05-12 at 9 07 55 PM](https://user-images.githubusercontent.com/1868782/118062968-20027480-b366-11eb-89fe-a7534670361b.png)

**Comment by mani-barathi** [comment]
@codyseibert  I've fixed this, I will give a PR.

**Comment by MidouWebDev** [comment]
@mani-barathi i assigned you

**Comment by MidouWebDev** [comment]
#360
