### ISSUE TITLE
Right Column hidden by header

### ISSUE THREAD

**Issue by codyseibert** [divanov11/Mumble#357]
When scrolling on the page, the right side column gets hidden by the header.

![Screen Shot 2021-05-12 at 9 30 40 PM](https://user-images.githubusercontent.com/1868782/118064587-4d9ced00-b369-11eb-977e-f35b0bce8b3d.png)

**Comment by codyseibert** [comment]
![Screen Shot 2021-05-12 at 9 35 17 PM](https://user-images.githubusercontent.com/1868782/118064895-f3505c00-b369-11eb-91a2-ebb1e85b1bc5.png)

**Comment by Mr-spShuvo** [comment]
@codyseibert  that is expected on the first case. 
Cause this is sticky and will scroll to all the cards on right hand side.

**Comment by divanov11** [comment]
I agree @Mr-spShuvo. This is how twitter does it and it will make more sense when we have more content in the sidebars
![Twitter sidebar](https://user-images.githubusercontent.com/33843378/118170894-9f408880-b3f8-11eb-9fde-d0d4e0f1118c.PNG)

**Comment by divanov11** [comment]
I'll close this issue unless there is something else here
