### ISSUE TITLE
FEAT: Header Bar

### ISSUE THREAD

**Issue by i-am-zach** [divanov11/Mumble#36]
React UI component that should be displayed on the top of every page. This should probably not be implemented until the discord has decided on Mumble's logo officially.

**Comment by divanov11** [comment]
Ageed

**Comment by MidouWebDev** [comment]
Yeah we will decide tomorrow i think because we are waiting for the fourth logo so that we can create a poll in the discord server and decide about the new MUMBLE logo.

**Comment by codyseibert** [comment]
I think @divanov11 created this already here: https://github.com/divanov11/Mumble/blob/master/frontend/src/Components/Header.js
