### ISSUE TITLE
Discord Link not working.

### ISSUE THREAD

**Issue by desaidhruv** [divanov11/Mumble#362]
### Describe the bug

The Discord link in Readme File is invalid.

#

### Screenshots

Here is the Screenshot for the same.
![image](https://user-images.githubusercontent.com/40533390/118163502-adfe5e00-b43f-11eb-857a-d64d5601ac1f.png)

**Comment by MidouWebDev** [comment]
Okey i will fix it

**Comment by desaidhruv** [comment]
This issue is solved, please close the issue.

**Comment by divanov11** [comment]
Thank you Mehdi, I will close the issue
