### ISSUE TITLE
Adding The Delete Mumble Option to Remumbled Post !

### ISSUE THREAD

**Issue by PraveenMalethia** [divanov11/Mumble#363]
![image](https://user-images.githubusercontent.com/59171685/118215390-132d7000-b48f-11eb-90f6-11fd3e95dbbc.png)

# With Hide, Unfollow, and Block, There should be also an option to delete the Remumbled Post! 

## Solution: The Delete Endpoint for Personal Mumble post can be used to delete the Remumbled Post!

**Comment by mani-barathi** [comment]
I'll work on this

**Comment by MidouWebDev** [comment]
@mani-barathi i assigned you
