### ISSUE TITLE
Unfollow Button Needs Logic - User Feed

### ISSUE THREAD

**Issue by codyseibert** [divanov11/Mumble#366]
The unfollow user in the mumble action menu does not do anything.  We should make that button unfollow the user and refresh your user feed.

![Screen Shot 2021-05-14 at 11 07 44 AM](https://user-images.githubusercontent.com/1868782/118290715-bd63c280-b4a4-11eb-919e-22d85faa66e7.png)

**Comment by MidouWebDev** [comment]
@codyseibert please don't forget next time to add your issues or PRs to the Project Board !

**Comment by mani-barathi** [comment]
@codyseibert @PraveenMalethia 
Is the backend updated and deployed with the unfollow user route?
