### ISSUE TITLE
Use Search not refreshing with the latest values

### ISSUE THREAD

**Issue by codyseibert** [divanov11/Mumble#367]
Go to the user search page, click the load more button, type zebra in the search inbox, notice that a bunch of results not related to zebra are still displayed in the UI

![Screen Shot 2021-05-14 at 11 37 28 AM](https://user-images.githubusercontent.com/1868782/118294660-f140e700-b4a8-11eb-9397-a7f20b057f93.png)

**Comment by jayshah-07** [comment]
Can you assign this issue to me

**Comment by MidouWebDev** [comment]
> @codyseibert  Can you assign this issue to me?

@jayshah-07 i assigned you !

**Comment by jayshah-07** [comment]
@MidouWebDev  I'm not able to commit my changes.
```
$ git push -u origin search-list-refresh 
remote: Permission to divanov11/Mumble.git denied to jayshah-07.
fatal: unable to access 'https://github.com/divanov11/Mumble.git/': The requested URL returned error: 403
```

![image](https://user-images.githubusercontent.com/4672245/118364352-c4c6c100-b5b5-11eb-99f7-719858f2bf25.png)

**Comment by MidouWebDev** [comment]
@jayshah-07 i see that you cloned the main repo ? did you fork the repo ?

**Comment by jayshah-07** [comment]
@MidouWebDev I've added my changes but it failed to deploy while creating a pull request. Moreover, I can't see details of the fail.

https://vercel.com/divanov11/mumble/C3bYTB7Vy9PZHb1gX9zByVtD4c8e [Preview link for error] => through 404

Is there something I'm doing wrong with the pull request?

![image](https://user-images.githubusercontent.com/4672245/118401157-22284400-b682-11eb-8071-1f120b1344bc.png)
