### ISSUE TITLE
There is a bug in the layout of the login/register pages

### ISSUE THREAD

**Issue by MidouWebDev** [divanov11/Mumble#378]
### Preflight Checklist

* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

#

### Describe the bug

There is a bug in the layout of the login page

#

### To Reproduce

1. Go to 'mumble.dev' (don't sign in)
2. See error in the login page

#

### Expected behavior

i expected to see this :

![loginpage](https://cdn.discordapp.com/attachments/828296378765672509/843208455816740904/unknown.png)

#

### Screenshots

The Error :

![bug](https://user-images.githubusercontent.com/72341453/118360360-b60ce980-b576-11eb-8a83-b2f230cb61ce.png)

**Comment by Emmanuel-Dominic** [comment]
@MidouWebDev, I think I work on this now.
Thanks

**Comment by MidouWebDev** [comment]
@Emmanuel-Dominic i will assign you

**Comment by MidouWebDev** [comment]
#384
