### ISSUE TITLE
update the endpoint for Delete Mumble ! 

### ISSUE THREAD

**Issue by PraveenMalethia** [divanov11/Mumble#380]
# New Endpoint for deleting at mumble backend is updated 
# Because the previous endpoint will make more sense to use as a detail endpoint for a single Mumble 

* Old Endpoint :
![image](https://user-images.githubusercontent.com/59171685/118413846-068f5e80-b6bf-11eb-9929-e198804e18b0.png)

* New endpoint :

![image](https://user-images.githubusercontent.com/59171685/118413837-faa39c80-b6be-11eb-9557-a1258f14ef74.png)

**Comment by mani-barathi** [comment]
@PraveenMalethia 
I tried making a request to the below new endpoint for deleting mumble, 
`https://mumbleapi.herokuapp.com/api/mumbles/delete/0fa88a80-2163-4abf-8029-63a9f8934ba6/` 
but it gave a **404** response.
I guess the backend is not deployed after the changes?
