### ISSUE TITLE
After updating my skills it doesn't update in the frontend

### ISSUE THREAD

**Issue by sheyziSilver** [divanov11/Mumble#386]
### Preflight Checklist

* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

#

### Describe the bug

After updating my skills on my profile the skills get updated in the backend but not on the frontend.

Your skills wouldn't even be updated after several refresh but it would be updated on the form input if you try changing it again.

#

### To Reproduce

1. Go to profile page
2. Change your skills and click the update button
3. Then cancel
4. You would still see what was formerly there but when you try updating again you see the former changes on the form input

#

### Expected behavior

I was expecting the form to automatically cancel and the skills in my profile page should automatically get updated. Even if it isn't updated after a refresh it should

#

### Add additional instructions and considerations for the assignee

- [ ] Jupiter

- [ ] Saturn

- [ ] Neptune

#

### Screenshots

![Screenshot_20210518-063324](https://user-images.githubusercontent.com/80963324/118597028-0e74fe80-b7a4-11eb-97e6-7a8bbea1bfa6.png)
![Screenshot_20210518-063329](https://user-images.githubusercontent.com/80963324/118597033-103ec200-b7a4-11eb-9aef-15f9a0aa430a.png)

#

### Additional context

Add any other context about the problem here (include commit numbers and branches if relevant)

**Comment by okumujustine** [comment]
can I work on this? @Mr-spShuvo

**Comment by MidouWebDev** [comment]
@okumujustine i can assign you if you wanna work on it

**Comment by MidouWebDev** [comment]
@okumujustine i can assign you if you wanna work on it

**Comment by MidouWebDev** [comment]
@okumujustine 

By the way there is a similar issue but related to email address

 https://github.com/divanov11/Mumble/issues/374

**Comment by okumujustine** [comment]
ooh okay, let me read through issue #374 as well

**Comment by MidouWebDev** [comment]
@okumujustine ok, thanks bro !

**Comment by okumujustine** [comment]
@MidouWebDev , I don't know if you have noticed this but, looks like the backend doesn't update the profile.

the update API seems not to be updating the skills

**Comment by MidouWebDev** [comment]
> @MidouWebDev , I don't know if you have noticed this but, looks like the backend doesn't update the profile.
> 
> the update API seems not to be updating the skills

Yeah, that's true !
@PraveenMalethia

**Comment by okumujustine** [comment]
I think I should do this as long as the API is ready.
Meanwhile am thinking of raising the issue in the API repo if it isn't raised yet, and as well do it...

**Comment by MidouWebDev** [comment]
> I think I should do this as long as the API is ready.
> Meanwhile am thinking of raising the issue in the API repo if it isn't raised yet, and as well fix it...
> @PraveenMalethia , @MidouWebDev 

Okey, cool :wink:
Thanks bro ! 
@okumujustine

**Comment by codyseibert** [comment]
@okumujustine are you cool if I just include a fix for this?  I worked on the backend endpoints and I just had to change it a couple of places in the UI to get the UI working.

**Comment by okumujustine** [comment]
> @okumujustine are you cool if I just include a fix for this? I worked on the backend endpoints and I just had to change it a couple of places in the UI to get the UI working.
It's okay, cool
