### ISSUE TITLE
duplicate user with same id

### ISSUE THREAD

**Issue by jayshah-07** [divanov11/Mumble#389]
### Preflight Checklist

* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

#

### Describe the bug

 inside search box type "jay" and select [search by user]. Backend return 3 user with same detials.

If you type "jays" it returns a single user, Thus it looks like DB records duplicate data even though the username is unique.

#

### To Reproduce

1. Go to 'search box and type jay as input for search'
2. Click on 'search by user'
3. Scroll down to 'you will see the same user appears multiple times.' so now check the network tab and https://mumbleapi.herokuapp.com/api/users/?q=jays, it returns duplicate data
4. See attached image for a detailed description.

#

### Expected behavior

#

### Add additional instructions and considerations for the assignee

- [ ] Jupiter

- [ ] Saturn

- [ ] Neptune

#

### Screenshots

![image](https://user-images.githubusercontent.com/4672245/118633470-258d0e00-b7ef-11eb-8ff6-07baa380b47d.png)

#

### Additional context

Add any other context about the problem here (include commit numbers and branches if relevant)

**Comment by codyseibert** [comment]
I'm thinking this is a bug with the view.  Our database is set to have unique columns for username, so our api must be fetching duplicates or using pagination incorrectly

**Comment by jayshah-07** [comment]
@codyseibert please see attached image response tab. I've highlighted the response as the server returns a duplicate user.

![image](https://user-images.githubusercontent.com/4672245/119084666-d7ab1c80-ba1f-11eb-8c9e-90433fb0ce0d.png)

**Comment by codyseibert** [comment]
@jayshah-07 yup it's an issue with our "view" in the django api.  We call the logic on the backend "views".  I'll already have a fix for this, it just needs to be deployed.  Thanks for reporting this bug!
