### ISSUE TITLE
Redirecting to an article detail view based on search query isn't working

### ISSUE THREAD

**Issue by rshalem** [divanov11/Mumble#390]
### Preflight Checklist

[I have searched the issue tracker for this issue and couldnt find any, hence created a new one] 

#

### Describe the bug

When an article is searched for, it displays article if present, but redirecting to that searched article isn't working when clicked
#

### To Reproduce

1. Go to 'Homepage'
2. Click on Enter after search query is typed
3. Scroll down to 'the required query result if present in db'
4. See error (Here unable to go to that searched article)

#

### What was expected ?

To be redirected to the searched article when clicked on it

#

**Comment by Leopold-V** [comment]
Hi @rshalem,
I would be glad to work on this issue as my first contribution to mumble 👍.
