### ISSUE TITLE
Comment count isn't reflecting as soon as we comment, working in backend but failing in frontend

### ISSUE THREAD

**Issue by rshalem** [divanov11/Mumble#391]
### Preflight Checklist

* I have searched the issue tracker for an issue that matches the one I want to file, without success.

#

### Describe the bug

 Comment count isn't reflecting as soon as we comment, it's reflecting only after refreshing the page again. It should reflect as submission of comment is done.

#

### To Reproduce

1. Go to 'Article/Post'
2. Click on 'Comment'
3. Submit
4. See error (comment count not reflecting in the frontend

#

### Expected behavior

Should update the comment count as soon as it hits the backend

#

**Comment by LakshmanKishore** [comment]
I guess I can work on it @MidouWebDev

**Comment by MidouWebDev** [comment]
@LakshmanKishore cool i will assign you
