### ISSUE TITLE
Remove option of Unfollow for Non Following User ! 

### ISSUE THREAD

**Issue by PraveenMalethia** [divanov11/Mumble#392]
![image](https://user-images.githubusercontent.com/59171685/118842555-f22daa80-b8e6-11eb-955e-6727fbf83929.png)

The unfollow option is also showing for the user that we don't follow!

**Comment by MidouWebDev** [comment]
@PraveenMalethia don't forget to add your issues/PRs to the project board pleaase !!

**Comment by codyseibert** [comment]
grabbing this one
