### ISSUE TITLE
SignUp bug -Error with a  strange error message.

### ISSUE THREAD

**Issue by Gagan-Saffron** [divanov11/Mumble#395]
### Preflight Checklist

* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

#

### Describe the bug

There was a strange bug that  occured when i tried to sign up.
I was not able to signup for some unknown reason, and the error message that i got was bit strange -
it stated " permission denied for table auth_user".

#

### To Reproduce

#

### Expected behavior

#

### Add additional instructions and considerations for the assignee

- [ ] Jupiter

- [ ] Saturn

- [ ] Neptune

#

### Screenshots

#

### Additional context

Add any other context about the problem here (include commit numbers and branches if relevant)

**Comment by mani-barathi** [comment]
@Gagan-Saffron I guess this is regarding some problem in the backend.

**Comment by MidouWebDev** [comment]
@Gagan-Saffron 

thanks for reporting this issue !
Can you refer to the contribution guidelines, you forgot to add this to the project board and you didn't follow the issue template ! (steps to reproduce, expected behavior ...)

**Comment by codyseibert** [comment]
I think this was related to the heroku database hitting a limit.  Closing unless we see this error again
