### ISSUE TITLE
Header Dropdown

### ISSUE THREAD

**Issue by justin107d** [divanov11/Mumble#40]
Hi, I would like to add the dropdown functionality into header.js

Thanks,

![image](https://user-images.githubusercontent.com/35573658/113080387-d6d6d680-91a4-11eb-8f6c-5e7eeaf2239e.png)

**Comment by justin107d** [comment]
I think I am getting overzealous. There is not much to link to yet.

**Comment by Vyvy-vi** [comment]
I think you can keep the issue open and maybe open a PR after some time, when this can be implemented.
