### ISSUE TITLE
Profile Image in header not displaying

### ISSUE THREAD

**Issue by codyseibert** [divanov11/Mumble#413]
The profile image in the header seems to point to an undefined resource.  I think this bug is probably simple view change to point to the profile.image.  We display user's profile images in the mumbles, so the images are being hosted successfully.

to reproduce:
1. Login
2. Look at the header

<img width="918" alt="Screen Shot 2021-05-25 at 11 43 42 PM" src="https://user-images.githubusercontent.com/1868782/119599462-0b38ce80-bdb3-11eb-849c-db1d10899e9d.png">

<img width="321" alt="Screen Shot 2021-05-25 at 11 43 08 PM" src="https://user-images.githubusercontent.com/1868782/119599421-f6f4d180-bdb2-11eb-9b49-c0ef384a3e8d.png">

**Comment by niteshseram** [comment]
I would like to work on this issue

**Comment by MidouWebDev** [comment]
@niteshseram i assigned you 😉 
Happy coding !

**Comment by MidouWebDev** [comment]
#414
