### ISSUE TITLE
Removing the profile picture

### ISSUE THREAD

**Issue by niteshseram** [divanov11/Mumble#416]
### Is your feature request related to a problem? Please describe.

I think adding a feature to remove the profile picture we have set would be great

#

### Describe the solution you'd like

There should be an option to remove the profile picture we have set before. There can be some point in time, when user doesn't want to have any profile picture. Currently, we can only change profile picture but cannot remove the one we have set.

#

**Comment by MidouWebDev** [comment]
@niteshseram please follow the contributions guidelines !!

https://midouwebdev.gitbook.io/mumble-docs/contributing/contributing

You didn't add your issue to the project board !
It is necessary for contributors to see which issue is available !!

Please take a look at https://midouwebdev.gitbook.io/mumble-docs/contributing/contributing

**Comment by MidouWebDev** [comment]
> @MidouWebDev I was looking for way to add the issue in the Project Board when I created this issue. But I don't see that option to add the issue to the project board. In the right side, the project section doesn't show that setting icon.

okey bro, no problem i will check this

**Comment by niteshseram** [comment]
> okey bro, no problem i will check this

I think we don't have permission to add the issue to the project board. May be only you guys can do.

**Comment by MidouWebDev** [comment]
i will work on the frontend part
