### ISSUE TITLE
Add a shortcut for focussing the search bar

### ISSUE THREAD

**Issue by akzain** [divanov11/Mumble#418]
### Is your feature request related to a problem? Please describe.

Adding a shortcut for focussing the search bar input would be nice 
#

### Describe the solution you'd like

On a keypress for example: '/' should focus the search bar

**Comment by MidouWebDev** [comment]
@akzain please follow the contributions guidelines !!

https://midouwebdev.gitbook.io/mumble-docs/contributing/contributing

You didn't add your issue to the project board !
It is necessary for contributors to see which issue is available !!

Please take a look at https://midouwebdev.gitbook.io/mumble-docs/contributing/contributing

**Comment by MidouWebDev** [comment]
@akzain 

i added it this time but try to do it next time 
Thanks !
