### ISSUE TITLE
Post comment Delete not updating

### ISSUE THREAD

**Issue by LakshmanKishore** [divanov11/Mumble#421]
### Preflight Checklist

* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

#

### Describe the bug

When you submit a comment and try to delete that comment after sometime. The comment is not deleting after you press the delete button. Rather the comment gets deleted when the page refresh.

#

### To Reproduce

1. Go to 'Posts'
2. Click on 'Comments icon'
3. Add New comment
4. Try deleting it.
5. The comment doesn't gets deleted
6. Refresh the page
7. Comment is now deleted.

#

### Expected behavior

Once user clicks on the post Actions and select Delete button option. The particular comment should be deleted after pressing the delete button.

**Comment by ishitb** [comment]
Hello. I checked the code and I believe it this can solved using the same way that the adding of comments is being done. So every post has a "PostActions" which contains the adding of comments/posts. So every post has a comments state variable, and on every addition, this array is changed. 
I think this can be done for the deletion as well. 
Let me know if you like the solution.

**Comment by okumujustine** [comment]
incase this has not yet been done, I can work on it.

Let me know if I can take it up.✍️

**Comment by MidouWebDev** [comment]
@okumujustine i will assign you
