### ISSUE TITLE
Create Account delete Option with endpoint 

### ISSUE THREAD

**Issue by PraveenMalethia** [divanov11/Mumble#422]
Creating the UI and connecting the Delete Account endpoint at profile settings! 
The ENdpoint is created!
for any endpoint query? ask me!

**Comment by mani-barathi** [comment]
@MidouWebDev are you working on this? If not I'll work on this

**Comment by MidouWebDev** [comment]
@mani-barathi i wanted to, by adding a danger zone section in the settings page where we will have the delete account option but if you wanna start now no problem go ahead cuz i planned to start working on it in June 1st

**Comment by mani-barathi** [comment]
@MidouWebDev For the latest changes, should I pull from master or develop?

**Comment by MidouWebDev** [comment]
@mani-barathi develop

**Comment by codyseibert** [comment]
@mani-barathi actually, we are just going to revert back to master based development.  Getting everyone to make changes to the develop branch is too much extra work.  Make your PR to the master branch. TY!

**Comment by mani-barathi** [comment]
@PraveenMalethia, @codyseibert 
I'm trying to send a POST request to `/api/users/delete-profile` , but the response fails stating the method is not allowed. I've also checked the backend, the view states it requires a POST request.  
I'm confused about whether something is wrong in the backend or in the request.

![image](https://user-images.githubusercontent.com/49336839/120142343-cb7f4600-c1fb-11eb-9cfb-9f1e6facb485.png)

![image](https://user-images.githubusercontent.com/49336839/120142618-2d3fb000-c1fc-11eb-9649-fa899a07ec48.png)

**Comment by codyseibert** [comment]
@mani-barathi it might not be deployed yet.  You could try running the api locally?

**Comment by mani-barathi** [comment]
@codyseibert ok I'll try running it locally!

**Comment by MidouWebDev** [comment]
@mani-barathi did you finish the frontend part ?
DM me on Discord plz

**Comment by mani-barathi** [comment]
@MidouWebDev yeah!

**Comment by MidouWebDev** [comment]
#439
