### ISSUE TITLE
Email Updation and User Information

### ISSUE THREAD

**Issue by ShyamSundhar1411** [divanov11/Mumble#425]
Email is not getting updated probably it is commented out in the signals then While inspecting using DEV tools The user information card is not getting displayed. Hope you guys will look on to it.
Thank You Sir

**Comment by ishitb** [comment]
Hi @ShyamSundhar1411 Please check the listed issues, this bug is already registered and being taken care of in the backend.
[Existing Issue](https://github.com/divanov11/Mumble/issues/374)

**Comment by MidouWebDev** [comment]
#374
