### ISSUE TITLE
confirming logout message

### ISSUE THREAD

**Issue by akzain** [divanov11/Mumble#426]
### Is your feature request related to a problem? Please describe.

I accidentally pressed the logout button instead of pressing the settings button and I thought of having a confirmation message for logging out
#

### Describe the solution you'd like

The solution I would like is to have a confirmation message for logging out after the logout button is pressed

**Comment by MidouWebDev** [comment]
@akzain i assigned you 😉

**Comment by MidouWebDev** [comment]
#430
