### ISSUE TITLE
🐛 A serious problem in up/downvoting

### ISSUE THREAD

**Issue by MidouWebDev** [divanov11/Mumble#428]
### A GIF to understand :

![bigissue](https://user-images.githubusercontent.com/72341453/120504789-5444e000-c3bc-11eb-9c3c-147dc7f59a5e.gif)

**Comment by Leopold-V** [comment]
Hey, can i work on this @MidouWebDev ?

**Comment by MidouWebDev** [comment]
Sure @Leopold-V 
Thank you
