### ISSUE TITLE
🐛 A serious bug related to the icons colors in the dark mode

### ISSUE THREAD

**Issue by MidouWebDev** [divanov11/Mumble#434]
## A GIF to understand :

![colors-issue](https://user-images.githubusercontent.com/72341453/120796409-b162a200-c532-11eb-9e14-3d972f239681.gif)

**Comment by MidouWebDev** [comment]
Please if you want to work on it, tag me here so that i can assign you ! 😉

**Comment by ishitb** [comment]
@MidouWebDev Hi can I be assigned for this?

**Comment by MidouWebDev** [comment]
@ishitb sure !

**Comment by ishitb** [comment]
@MidouWebDev I think there is some linting issue which cause the github actions workflow to fail. It's just formatting issues in 2 css files. Should I address them with this only or open up a new issue?

**Comment by MidouWebDev** [comment]
@ishitb create a new issue and when you fix the new one commit then and go back to fixing icons colors and commit then 
DM me on discord if you didn't understand what i have written here

**Comment by ishitb** [comment]
> @ishitb create a new issue and when you fix the new one commit then and go back to fixing icons colors and commit then
> DM me on discord if you didn't understand what i have written here

Alright, got it! Thanks 😄

**Comment by MidouWebDev** [comment]
@ishitb i merged your PR related to Github Actions, you did a good job !
Looking forward your contribution to this issue 🙏🏻

**Comment by ishitb** [comment]
Thank you @MidouWebDev 😁 Almost done. I'll create a pull request in 20 minutes

**Comment by MidouWebDev** [comment]
@ishitb take your time bro
