### ISSUE TITLE
Blue background on tapping the theme toggler button in logout page in mobiles

### ISSUE THREAD

**Issue by akzain** [divanov11/Mumble#435]
### Preflight Checklist

* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

#

### Describe the bug
When you go to the logout page and tap the theme toggler button in mobiles you will notice a blue background

#

### Video
https://user-images.githubusercontent.com/80206683/120762777-3f349200-c51f-11eb-9ee0-b1d6d6bcf651.mp4
#

### Expected behavior

There shouldn't be a blue background on tapping the theme toggler button in logout page in mobiles.
#

**Comment by akzain** [comment]
I would like to work on this @MidouWebDev

**Comment by MidouWebDev** [comment]
Happy coding, @akzain !
i assigned you :wink:

**Comment by MidouWebDev** [comment]
#436
