### ISSUE TITLE
FIX: Post Form (HomePage) Outline

### ISSUE THREAD

**Issue by ujjawal-shrivastava** [divanov11/Mumble#44]
Current PostForm component's text area shows the default css outline.

Either it could be set to none (for which I can create a PR) or we can use the new form fields created by Shuvo.

![CURRENT_OUTLINE](https://user-images.githubusercontent.com/57309688/113086472-4b3e6380-91ff-11eb-9917-dc6df987519e.png)

**Comment by codyseibert** [comment]
Having the outline is good for accessibility when the component is focused.  I don't think this should be adressed
