### ISSUE TITLE
Crash when click on the search by posts page.

### ISSUE THREAD

**Issue by Leopold-V** [divanov11/Mumble#442]
### Preflight Checklist

* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

#

### Describe the bug

When we try to search by posts the application crash. With error "TypeError: Invalid attempt to spread non-iterable instance."

#

### To Reproduce

https://gyazo.com/a07472d38aca298314e7e199566b5dbd

#

### Additional context

According to the error I think it is a prop type error somewhere in the post components. I can fix it.

**Comment by MidouWebDev** [comment]
@Leopold-V i assigned you

**Comment by MidouWebDev** [comment]
#446
