### ISSUE TITLE
Problem in voting

### ISSUE THREAD

**Issue by akzain** [divanov11/Mumble#445]
### Describe the bug

If you up vote a post and then down vote the same post it deducts 2 votes instead of deducing 1 vote.

#

### To Reproduce

1. Go to 'A post'
2. Click on 'up vote button.'
3. Then click 'down vote button'
4. See  the error

#

### Expected behavior

The post should only deduct 1 vote if a user who already up voted a post and then down voted the same post.

#

**Comment by akzain** [comment]
I would love to work on this issue @MidouWebDev

**Comment by MidouWebDev** [comment]
@akzain i assigned you
Happy Coding ! 😉

**Comment by MidouWebDev** [comment]
#448
