### ISSUE TITLE
Github Actions Workflow not passing

### ISSUE THREAD

**Issue by ishitb** [divanov11/Mumble#449]
### Preflight Checklist
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

#

### Describe the bug

The workflow defined has been failing due to some minor formatting issues which causes the lint and formatting scripts to fail.

#

### To Reproduce

1. Go to [Actions Tab](https://github.com/divanov11/Mumble/actions)
2. Click on any of the failed workflow runs
3. See error

#

### Expected behavior

The workflow should essentially give no errors and should pass so that in future tests can be run automatically as well.

#

### Screenshots

![image](https://user-images.githubusercontent.com/53562523/120902301-33e78080-c65d-11eb-8994-511412fba4ab.png)

#

### Possible Solution

Formatting the files, indicated by the error, can resolve the issue. For future, any new contributor could run the linting and formatting tests locally to check their code.

**Comment by MidouWebDev** [comment]
@ishitb do you want to work on it ?

**Comment by ishitb** [comment]
@MidouWebDev Yes I'll work in it for the latest commit currently

**Comment by MidouWebDev** [comment]
@ishitb okey cool
Please don't forget to tag me as a reviewer when you submit your PR

**Comment by MidouWebDev** [comment]
@ishitb awesome work bro
It is working now !
