### ISSUE TITLE
🐛 A serious problem in the Login/Signup/Forgotpwd UI 

### ISSUE THREAD

**Issue by MidouWebDev** [divanov11/Mumble#455]
![UI-Issue](https://user-images.githubusercontent.com/72341453/120923458-91fc7e00-c6c6-11eb-81bb-c2a4deed054a.jpg)

**Comment by akzain** [comment]
I would like to work on this @MidouWebDev

**Comment by MidouWebDev** [comment]
Sure, thanks @akzain !

**Comment by MidouWebDev** [comment]
https://github.com/divanov11/Mumble/commit/571ba6779d9546691b0d7e1ce2c19a419488acd3
