### ISSUE TITLE
Add a 'Scroll To Top' feature

### ISSUE THREAD

**Issue by akzain** [divanov11/Mumble#458]
### Is your feature request related to a problem? Please describe.
A scroll to top feature would be great for the homepage.

#

### Describe the solution you'd like

If a user scrolls down he should see a button on the bottom on which if he clicks he gets scrolled back to top.

#

**Comment by akzain** [comment]
I would like to work on this feature @MidouWebDev

**Comment by MidouWebDev** [comment]
I think it is a great feature to add to Mumble. Let's take @Mr-spShuvo 's opinion !

**Comment by MidouWebDev** [comment]
After DM-ing @Mr-spShuvo , he told me that we don't need this in Mumble.
Sorry @akzain !
