### ISSUE TITLE
Bugs on Login/Signup page

### ISSUE THREAD

**Issue by RadhiRasho** [divanov11/Mumble#460]
### Preflight Checklist

* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

#

### Describe the bug

There are cases on the login/registration page where popups are showing but they are behind the main login/signup area.
Picture provided below.

This same issue happens with the discord and midouwebdev.gitbook.io link icon as well. Also, the Continue with Github as well as the Continue with Google buttons on the same page don't do anything when clicked (Are these two buttons placeholders?).

#

### To Reproduce

1. Go to 'mumble.dev/login'
2. Click on the continue with GitHub and google buttons (again these might just be placeholders)
3. Hover over Github, discord, and Gitbook/file Icons on the bottom of the screen.

#

### Expected behavior

I expect the buttons (if not placeholder) to open a popup or go to the page to log in using google/GitHub email and password.

I expect on hover popup to show above the login/registration section instead of below it.

#

### Screenshots

![image](https://user-images.githubusercontent.com/54078496/122685589-eed15b80-d1d1-11eb-844f-082acad16bb5.png)

**Comment by okumujustine** [comment]
I can work on this if it's clarified @codyseibert

**Comment by RadhiRasho** [comment]
@okumujustine my assumption is that the popover/tooltip is meant to appear telling the user what that icon/link leads to, similar to alt for the img tag.

**Comment by okumujustine** [comment]
ooh okay @RadhiRasho .

@Mr-spShuvo  assign me this task in case no one is working on it.

Thank you

**Comment by Mr-spShuvo** [comment]
Hello Everyone. The login and signup page will be redesigned completely. 
That's why No more PR on Login and Signup Page will be merged. for now.
Thank you.
