### ISSUE TITLE
This is a crap webapp 

### ISSUE THREAD

**Issue by dheerajsinghnagdali** [divanov11/Mumble#467]
### Preflight Checklist

* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

#

### Describe the bug

#

### To Reproduce

#

### Expected behavior

#

### Add additional instructions and considerations for the assignee

- [ ] Jupiter

- [ ] Saturn

- [ ] Neptune

#

### Screenshots

#

### Additional context

Add any other context about the problem here (include commit numbers and branches if relevant)

**Comment by dennisivy** [comment]
Useless comment, issue closed.

**Comment by PraveenMalethia** [comment]
LOL

**Comment by ghost** [comment]
why did he write such a useless comment!!??
