### ISSUE TITLE
FIX: Broken Link

### ISSUE THREAD

**Issue by einsatz3012** [divanov11/Mumble#49]
Link to Code of Conduct inside [CONTRIBUTING.md](https://github.com/einsatz3012/Mumble/blob/master/CONTRIBUTING.md)  is not working, giving Not Found.

![Screenshot_2021-03-31 divanov11 Mumble](https://user-images.githubusercontent.com/54238597/113092992-b0e51c80-920c-11eb-8ecc-cc49620aed78.png)

**Comment by Vyvy-vi** [comment]
Wupps, #27 slip-up
The link should be-
https://github.com/divanov11/mumble/blob/master/CODE_OF_CONDUCT.md

**Comment by itzomen** [comment]
This type of minor updates can be noted somewhere, so that when there are 2 or more similar updates; they can be fixed all at once to avoid a lot of pull requests of this sort

**Comment by Vyvy-vi** [comment]
for anyone looking to fix this issue, kindly have a look at these too and make a PR for all of them:
- [ ] #49 - Broken CODE_OF_CONDUCT link in CONTRIBUTING.md
- [ ] #16 - Typo in README

I think we can keep a list of all such issues in the top-most issue, maybe?

**Comment by itzomen** [comment]
> for anyone looking to fix this issue, kindly have a look at these too and make a PR for all of them:
> 
> * [ ]  #49 - Broken CODE_OF_CONDUCT link in CONTRIBUTING.md
> * [ ]  #16 - Typo in README
> 
> I think we can keep a list of all such issues in the top-most issue, maybe?

Yes that's a great idea 💡

**Comment by einsatz3012** [comment]
While pushing changes I got some errors because I cloned the Dennis' main repository to my machine instead of cloning my forked repository, so to avoid confusion this point in [CONTRIBUTING.md](https://github.com/divanov11/Mumble/blob/master/CONTRIBUTING.md#pull-requests) can be changed from

> 2. Clone the project to your machine 

to

> 2. Clone the forked repository from your github account to your machine
**If this is the correct solution.**

**Comment by einsatz3012** [comment]
> 
> 
> While pushing changes I got some errors because I cloned the Dennis' main repository to my machine instead of cloning my forked repository, so to avoid confusion this point in [CONTRIBUTING.md](https://github.com/divanov11/Mumble/blob/master/CONTRIBUTING.md#pull-requests) can be changed from
> 
> > 1. Clone the project to your machine
> 
> to
> 
> > 1. Clone the forked repository from your github account to your machine
> 
> **If this is the correct solution.**

@Vyvy-vi  can you check this out?

**Comment by Vyvy-vi** [comment]
I think #53 added the change

**Comment by Mr-spShuvo** [comment]
fixed!
