### ISSUE TITLE
FIX: Add Gitignore file 

### ISSUE THREAD

**Issue by felixfaisal** [divanov11/Mumble#51]
We can have a global gitignore file for both React and Django 

This is useful, as someone would mistakenly push the nodejs modules or pycache in django. 
I'm assuming that the backend would be written in django

**Comment by felixfaisal** [comment]
I would like to work on adding this :)

**Comment by itzomen** [comment]
> We can have a global gitignore file for both React and Django
> 
> This is useful, as someone would mistakenly push the nodejs modules or pycache in django.
> I'm assuming that the backend would be written in django

Yes the backend will be written in Django
I think we should wait for the backend base files and the create-react-app creates the .gitignore file for the frontend folder

**Comment by Vyvy-vi** [comment]
I think there's a .gitignore file for the frontend added by one of the PRs

**Comment by Mr-spShuvo** [comment]
a `.gitignore` file has been added on `frontend` dir
