### ISSUE TITLE
Possible bug with the user search page, needs actual functionality

### ISSUE THREAD

**Issue by SamTheFam** [divanov11/Mumble#55]
Will fix bug and add better functionality.

Edit: Just realised I was using `require` for some reason, will fix that.

**Comment by samuelwondimu** [comment]
i have done the search user and display the user i am going to create a pull request

**Comment by samuelwondimu** [comment]
#59 fixed user search

**Comment by Vyvy-vi** [comment]
I think there are too PRs open for this #56 and #59 
(maybe we can try and check out if a PR has been already opened for an issue. This leads to multiple PRs for the same stuff, and might make the maintainer decide on the 'better' PR)

I'll say, when one of the PRs doesn't get accepted, don't be disheartened, this happens from time to time.
You didn't do anything wrong and you can always contribute on another issue :heart:

**Comment by codyseibert** [comment]
@divanov11 is already working on this feature.
