### ISSUE TITLE
Website is not responsive for mobile

### ISSUE THREAD

**Issue by bharathjinka09** [divanov11/Mumble#58]
I checked the website in my local by forking the repository. I tested it in responsive mode. But it is not responsive.

**Comment by MidouWebDev** [comment]
I also noticed that and a friend is working on it @Rashik (his nickname in DISCORD)
Contact him !

**Comment by Rashik4567** [comment]
We are working on it. Site will be mobile friendly in 2 days following and wait for pull.

**Comment by Rashik4567** [comment]
Solved on pull request (#78 )

**Comment by bharathjinka09** [comment]
I am closing this issue. Thanks
