### ISSUE TITLE
Docs: Typo in README.md

### ISSUE THREAD

**Issue by vikasganiga05** [divanov11/Mumble#64]
Hi, there is a typo in `README.md` file. Multiple `=` signs which are not required.

![screenshot-github com-2021 03 31-19_22_14](https://user-images.githubusercontent.com/74750414/113158260-44443f00-9259-11eb-806c-50f52c2fd3a5.png)

**Comment by MidouWebDev** [comment]
Yess !

**Comment by codyseibert** [comment]
fixed in #67
