### ISSUE TITLE
Create High Order Component

### ISSUE THREAD

**Issue by jewells07** [divanov11/Mumble#70]
Creating a High Order Component (HOC) for manage layouts and clean in the App.js file.
**Advantage** : Header, Navbar, Alert messages, etc.. will be in `HOC file` and render that one component into in `App.js file`

**Comment by codyseibert** [comment]
I'm not sure what you mean by this issue.  Could you please elaborate by providing an example code snippet to describe what you mean?

**Comment by jewells07** [comment]
**Before**
```javascript
function App() {
  return (
    <Router>
      <Header />
      <Switch>
        <Route exact path={'/login'} component={LoginPage} />
        <main>
          <Route exact path={'/'} component={HomePage} />
          <Route exact path={'/profile/:username'} component={ProfilePage} />
          <Route exact path={'/settings'} component={UserSettingsPage} />
          <Route exact path={'/discussion/:slug'} component={Discussion} />
          <Route exact path={'/find-user'} component={UserSearchPage} />
        </main>
      </Switch>
    </Router>
  );
}
```

**After**
```javascript
import Hoc from './layout/Hoc';

 function App() {
  return (
    <Router>
      <Hoc>
      <Switch>
        <Route exact path={'/login'} component={LoginPage} />
        <main>
          <Route exact path={'/'} component={HomePage} />
          <Route exact path={'/profile/:username'} component={ProfilePage} />
          <Route exact path={'/settings'} component={UserSettingsPage} />
          <Route exact path={'/discussion/:slug'} component={Discussion} />
          <Route exact path={'/find-user'} component={UserSearchPage} />
        </main>
      </Switch>
      </Hoc>
    </Router>
  );
}
```
**Example** : Common components will in (Hoc), Layouts can have Navbar, Header, Alert, etc... and put into (Hoc). So it will be clean code.

**Comment by codyseibert** [comment]
I personally don't see the issue with having <Header /> being above the switch.  The current code doesn't seem unclean to me, but I'll let others weigh in on this issue.  We could also just move the <Switch> into a new component called <Content> and import it here if that helps?

**Comment by jewells07** [comment]
When this app getting larger, we will have 'check authenticated' , 'load user' etc with redux that time this will very helpful.
