### ISSUE TITLE
Add link to the site in the repo description

### ISSUE THREAD

**Issue by Vyvy-vi** [divanov11/Mumble#9]
### Description-
This would help in linking people to the deployed version faster and it would also maybe help in the embed's generated for the project.

### Is this really important?-
Not really, but can add a small utility

### Screenshot of how this looks-
![Screenshot 2021-03-30 at 9 23 52 PM](https://user-images.githubusercontent.com/62864373/113018623-5c0abd00-919e-11eb-9f00-8dab2429abb0.png)

**Comment by Mr-spShuvo** [comment]
@divanov11 It's up to you.

**Comment by divanov11** [comment]
Will add it once we get a version up

**Comment by Mr-spShuvo** [comment]
added.
