### ISSUE TITLE
Typo in About section of GitHub. built for "develpers"

### ISSUE THREAD

**Issue by bharathjinka09** [divanov11/Mumble#95]
built for develpers. It should be developers

**Comment by codyseibert** [comment]
@bharathjinka09 could you make a pr to fix this typo plz?

**Comment by Mr-spShuvo** [comment]
It's on the about section, How can he do a PR? lol
@divanov11 , would you mind fix this?

**Comment by codyseibert** [comment]
@Mr-spShuvo ohh my bad! yeah Dennis would have to fix it. Ignore me!

**Comment by MidouWebDev** [comment]
@divanov11 i mentionned the typo it has been a week i guess and the mistake is still here 😂 
![image](https://user-images.githubusercontent.com/72341453/113518908-1294e600-9581-11eb-970b-ba5cc008d427.png)
