### ISSUE TITLE
Improving folder structure and adding react component test files

### ISSUE THREAD

**Issue by agentraghav** [divanov11/Mumble#96]
-  react component test files are not there, we can add test files to test react components by running `npm test`
- improve folder structure, like keeping every component in a separate folder with their corresponding test files.

**Comment by Mr-spShuvo** [comment]
Any principals and style guides you want us to follow or it's just a suggestion? @agentraghav

**Comment by agentraghav** [comment]
it's a suggestion and yaa there are few rules that must be followed or it will be good for contributors if they are followed like
- Every component should be in a separate folder with the corresponding testing file.
- It is good to keep the styling file of that component in that folder instead of creating a separate styles folder. 
-  file naming should be in lower case, use a (-) dash or underscore ( _ ) instead of using camel case.

**Comment by agentraghav** [comment]
@Mr-spShuvo  I can raise a PR with improved folder structure and including test files, if you find that useful, you can merge that

**Comment by Mr-spShuvo** [comment]
Thanks for your personal suggestions, but we are not looking for any changes to current directory structures. As there are no hard and fast rules, and everybody prefers different working tree, we just want to stick to the current folders and files structures. May be in future we can change that, but currently our main focus is releasing the MVP asap.

**Comment by agentraghav** [comment]
okay
