### ISSUE TITLE
Reducing size of the avatar in Comments section of the Posts

### ISSUE THREAD

**Issue by mani-barathi** [divanov11/Mumble#99]
I Think the size of the avatar in Comments is equal when compared to the avatar of the Post itself. Should we reduce the size of it from 'md' to 'sm', because right now its kinda confusing whether it is a Post or a Comment

**Befor**
![image](https://user-images.githubusercontent.com/49336839/113404698-32cc7580-93c6-11eb-8966-092ddbc5004f.png)

**After**
![image](https://user-images.githubusercontent.com/49336839/113404794-5ee7f680-93c6-11eb-9f72-f2af4cf22b9d.png)

**Comment by Mr-spShuvo** [comment]
This issue have be resolve with [this commit](https://github.com/divanov11/Mumble/commit/e0ac8bff12af50b663fc312e7aaeac4091af1339)
